### ISSUE TITLE
Use product keys as the name attribute

### ISSUE THREAD

**Issue by schisamo** [chef-cookbooks/chef-ingredient#1]
Chef end-users don't care about our history of naming things poorly. We should rename the `chef_ingredient` resource's `package_name` attribute to `product` and perform mappings for them.

Here is a canonical list of products and associated keys/packages.

| Product | Product Key  | Package Name |
| ---------- | ------------------ | -------------------- |
| Chef Client | chef | chef |
| Chef Development Kit | chefdk| chefdk |
| Enterprise Chef (legacy) | private-chef | private-chef |
| Chef Server | chef-server | chef-server (versions < 12.0.0) <br/> chef-server-core (versions >= 12.0.0) |
| Chef Server High Availability addon | chef-ha | chef-ha |
| Chef Server Replication addon | chef-sync | chef-sync |
| Chef Server Reporting addon | reporting | opscode-reporting |
| Management Console | manage | opscode-manage (versions < 2.0.0) <br/> chef-manage (versions >= 2.0.0) |
| Push Jobs Server | push-jobs-server | opscode-push-jobs-server |
| Push Jobs Client | push-jobs-client | opscode-push-jobs-client (versions < 2.0.0) <br/> push-jobs-client (versions >= 2.0.0)  |
| Analytics Platform | analytics | opscode-analytics |
| Delivery | delivery | delivery |
| Delivery CLI | delivery-cli | delivery-cli |
| Supermarket | supermarket | supermarket |

Additionally the `chef_ingredient` resource should validate the `product` attribute and raise a friendly error if an invalid product key is provided.

**Comment by schisamo** [comment]
Perhaps we should drop the leading `chef-*` on the chef-ha and chef-sync keys?

**Comment by binamov** [comment]
also de-opscode-ify reporting?

**Comment by jtimberman** [comment]
I think it's nice UX if we allow the package name in addition to the product key, and that is required for backwards compatibility for `chef_server_ingredient` use.

**Comment by schisamo** [comment]
@binamov It would be up to the Reporting product team to remove the `opscode-*` from their package.

**Comment by schisamo** [comment]
@jtimberman do we need that backward compatibility? I think we should move to simplify things. Why do I as an end-user care what are packages are named?

**Comment by jtimberman** [comment]
There's a bunch of cookbooks out there that are using the old and busted thing.

**Comment by jtimberman** [comment]
Note that most of those are written by Chef employees :cake:

**Comment by schisamo** [comment]
So the "Right Hard Thing" is to release this cookbook with the features we want and get others to upgrade to the new way (which people will).

**Comment by schisamo** [comment]
This is brand new cookbook, it's OK if consumers need to update their code.

**Comment by jtimberman** [comment]
The chef-server-ingredient cookbook was also a non 1.0 release, and they can also pin versions.

**Comment by jtimberman** [comment]
Not accounting for versions, other than chef-server11 is a separate entry. A product hash dump:

```ruby
{
  'chef' => {
    'package-name' => 'chef',
    'ctl-command' => nil
  },
  'chefdk' => {
    'package-name' => 'chefdk',
    'ctl-command' => nil
  },
  'private-chef' => {
    'package-name' => 'private-chef',
    'ctl-command' => 'private-chef-ctl'
  },
  'chef-server11' => {
    'package-name' => 'chef-server',
    'ctl-command' => 'chef-server-ctl'
  },
  'chef-server' => {
    'package-name' => 'chef-server-core',
    'ctl-command' => 'chef-server-ctl'
  },
  'chef-ha' => {
    'package-name' => 'chef-ha',
    'ctl-command' => nil
  },
  'chef-sync' => {
    'package-name' => 'chef-sync',
    'ctl-command' => 'chef-sync-ctl'
  },
  'reporting' => {
    'package-name' => 'opscode-reporting',
    'ctl-command' => 'opscode-reporting-ctl'
  },
  'manage' => {
    'package-name' => 'opscode-manage',
    'ctl-command' => 'opscode-manage-ctl'
  },
  'push-jobs-server' => {
    'package-name' => 'opscode-push-jobs-server',
    'ctl-command' => 'opscode-push-jobs-ctl'
  },
  'push-jobs-client' => {
    'package-name' => 'opscode-push-jobs-client',
    'ctl-command' => nil
  },
  'analytics' => {
    'package-name' => 'opscode-analytics',
    'ctl-command' => 'opscode-analytics-ctl'
  },
  'delivery' => {
    'package-name' => 'delivery',
    'ctl-command' => 'delivery-ctl'
  },
  'delivery-cli' => {
    'package-name' => 'delivery-cli',
    'ctl-command' => nil
  },
  'supermarket' => {
    'package-name' => 'supermarket',
    'ctl-command' => 'supermarket-ctl'
  }
}
```

**Comment by schisamo** [comment]
Since we'll already know the version (it's provided or inferred from 'latest') we should work that into whatever helper you create. We'll know that manage, push-jobs-client and chef-server all need this type of branching logic (since they've had package name changes over the years).

**Comment by jtimberman** [comment]
By inferred from latest, what do you mean? That we can assume the newer package names since they'll be the latest ones?

**Comment by schisamo** [comment]
Forget the latest version stuff for now, it's obviously confusing the issue being discussed here. :smile: 

The product version numbers are important as __manage__, __push-jobs-client__ and __chef-server__ already have different package names (and possibly ctl commands) depending on what version is being installed. Changes in the package names for __push-jobs-server__ and __reporting__ will be coming in the not-too-distant future also.

I definitely would not confuse the issue by introducing a `chef-server11` product key. This is just __chef-server__ at versions < 12.0.0. Remember we've already introduced `mixlib-versioning` as a dependency which should make version comparison logic very easy (`Mixlib::Versioning::Format` includes Comparable and implements the `<=>` operator).
