### ISSUE TITLE
Fedora support 

### ISSUE THREAD

**Issue by spheromak** [chef-cookbooks/chef-ingredient#11]
No support here for fedora from a repo perspective. I know you aren't pushing packages to packagecloud for fedora, but I think you cold use el7 for fedora20-22 just fine. 

Edit: I noticed in delivery-cluster repo that it's vendoring the old chef-server-ingredient. Same problem exists trying to provision on on fedora regardless I think.

**Comment by jtimberman** [comment]
1. Generally speaking, Fedora is not supported, specifically, for our server products. That said, you may be able to get it to work by using the package_source property on the chef_ingredient resource in your recipes, or by mangling the yum-chef cookbook's attributes. Also, if you're using Fedora 22, you might run into package installation issues with dnf's compatibility shim.

2. This cookbook was only just announced internally this morning, and to the community a few minutes ago - not that it's been secret, as obviously you found it :smile: :cake:. We're working on getting the chef-server and chef-server-cluster cookbooks updated to use it. I can't speak to what the delivery team will do with the delivery-cluster cookbook, though, as that's not in my current scope of work.
