### ISSUE TITLE
chef_ingredient fails to install opscode-push-jobs-server 1.1.5 and 1.1.6

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/chef-ingredient#113]
opscode-push-jobs-server versions 1.1.5 and 1.1.6 diverged from previous naming conventions, whereby the filename does not contain the platform designation, such as _el6_ for Redhat 6. This divergence breaks chef_ingredient's ability to fetch the package for installation on a target node.

Gist of the resulting error during a chef run is here: https://gist.github.com/haidangwa/ce81d027cc6d81b3ec23812f8c5cc08a

The recipe uses the chef_ingredient resource, like so:

```
chef_ingredient 'push-jobs-server' do
  version node['twdc_chef']['push-jobs-server']['package_version']
  notifies :reconfigure, "chef_ingredient[#{node.run_state['ha_ingredient']}]", :delayed
  notifies :reconfigure, 'chef_ingredient[push-jobs-server]', :delayed
end
```

In the recipe, `node['twdc_chef']['push-jobs-server']['package_version']` evaluates to 1.1.6.
## chef-client version

12.11.18
## node platform

RHEL 6 x86_64
## chef-ingredient version

0.18.5

**Comment by schisamo** [comment]
After chatting with @haidangwa they also have `node['chef-ingredient']['custom-repo-recipe']` set which triggers installation from a yum repo (vs the default `remote_file` + `package`).

**Comment by haidangwa** [comment]
@schisamo: I think you were onto something. With custom-repo-recipe completely unset and testing on a node that can reach out the Internet, chef_ingredient is able to install the package. I have to set custom-repo-recipe, because we mirror the Chef yum repository internally and configure our nodes to use this internal yum repo where the nodes cannot reach the Internet due to security policies on our datacenter.
```
Recipe: twdc_chef::push-jobs-server
         * chef_ingredient[push-jobs-server] action install
           - Download push-jobs-server package from https://packages.chef.io/stable/el/6/opscode-push-jobs-server-1.1.6-1.x86_64.rpm
           * ruby_block[stop chef run] action nothing (skipped due to action :nothing)
           * remote_file[/tmp/kitchen/cache/opscode-push-jobs-server-1.1.6-1.x86_64.rpm] action create
             - create new file /tmp/kitchen/cache/opscode-push-jobs-server-1.1.6-1.x86_64.rpm
             - update content in file /tmp/kitchen/cache/opscode-push-jobs-server-1.1.6-1.x86_64.rpm from none to 8377ef
             (file sizes exceed 10000000 bytes, diff output suppressed)
             - change mode from '' to '0644'
           * yum_package[push-jobs-server] action install
             - install version 1.1.6-1 of package opscode-push-jobs-server
```

**Comment by wrightp** [comment]
I see where the issue is. I'll start working on this. What I don't want to do is add hack code just for this package/version.
