### ISSUE TITLE
chef-ingredient omnitruck handler does not respect http proxies

### ISSUE THREAD

**Issue by scotthain** [chef-cookbooks/chef-ingredient#116]
When behind a proxy, using `chef_ingredient "chef-server"` for a platform that ends up using the omnitruck handler (not the default mixlib-install one) will fail.

@stephenlauck ran into this in the wild, feel free to add any information!

**Comment by stephenlauck** [comment]
Relevant error from the field: https://gist.github.com/stephenlauck/6a1d7f0e31220c622ffa6abb91befec3

**Comment by schisamo** [comment]
@stephenlauck @scotthain So I think the proper fix is to make `sles` use the default mixlib-install handler:
https://github.com/chef-cookbooks/chef-ingredient/blob/4ee41291ec721c9ea1e5a9c39db0b0d20b9d78d8/libraries/chef_ingredient_provider.rb#L40-L46

We might have to place a fix in mixlib-install so it knows to return the proper EL package when the platform is `sles`.

**Comment by stephenlauck** [comment]
Agree @schisamo should we file an issue on mixlib-install as the proper fix here?

**Comment by wrightp** [comment]
@scotthain here https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/default_handler.rb#L56 and https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/chef_ingredient_provider.rb#L40

we intentionally didn't try to add everything since we didn't have a great approach to testing it at the time.

I'll look into mixlib-install now and update here

**Comment by wrightp** [comment]
Ok, as far as I can tell mixlib-install shouldn't require any changes since sles is currently supported in bintray and artifactory. Should just work.

**Comment by schisamo** [comment]
@wrightp We'll need those special checks to include a platform family of `suse` (of which OpenSUSE and SLES falls under). Here is some example Ohai data from Fauxhai:
https://git.io/viJ8r
https://git.io/viJ8D
