### ISSUE TITLE
execute("chef-server-core-reconfigure") fails: FATAL: Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2)

### ISSUE THREAD

**Issue by pcbear** [chef-cookbooks/chef-ingredient#133]
### Cookbook version
chef-ingredient (0.21.3)

### Chef-client version
chef-client 12.15.19 and 12.18.31

### Platform Details
Oracle Linux Server release 6.8
Attempted with chef-server 12.8.0 and 12.12.0

### Scenario:
chef-server-ctl reconfigure fails to execute

### Steps to Reproduce:
chef-enterprise cookbook depends on chef-ingredient

recipe server contains the chef-ingredient resource:

chef_ingredient 'chef-server' do
  action :reconfigure
end

Attempted with both chef-solo and chef-client -z.

### Expected Result:
Expecting 'chef-server-ctl reconfigure' to execute without error

### Actual Result:
[2017-02-17T15:49:02+00:00] ERROR: chef_ingredient[chef-server] (chef-enterprise::server line 54) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[chef-server-core-reconfigure] (/root/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb line 105) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of chef-server-ctl reconfigure ----
STDOUT: [2017-02-17T15:49:02+00:00] FATAL: Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2)
STDERR: 
---- End output of chef-server-ctl reconfigure ----

chef-stacktrace.out
https://gist.github.com/pcbear/1c6f89e17e81f7c401edf27cc3460a22

chef-client run
https://gist.github.com/pcbear/46d3d3111c004217cbee1b74e71c6fa3

**Comment by kennonkwok** [comment]
@pcbear did this work for you on a previous version of the cookbook?

**Comment by kennonkwok** [comment]
@pcbear I just tried to repro this on the cookbook version 1.1.0, chef-client 12.19.36, and oel 6.8 from bento and seemed OK for me.

This was my test recipe:
```
chef_ingredient 'chef-server' do
  action [ :install, :reconfigure ]
end
```

**Comment by cheeseplus** [comment]
Is this system ipv6 only by chance?

**Comment by gravesb** [comment]
I'm seeing the same error during a packer build running chef-solo.  However if I remove the reconfigure lines from the recipe and spin up the resulting AMI, I can run reconfigure manually just fine.  I see the same behavior on chef-ingredient 0.21.4 and 2.0.4. Also tested on chef-client 12.17.44 and 12.19.36.

**Comment by gravesb** [comment]
FWIW, I was able to modify the /etc/hosts file and removed localhost and localhost.localdomain from the ::1 entry (so localhost was no longer mapped to an ipv6 address).  This resolved the issue for me.

**Comment by wrightp** [comment]
@gravesb Thanks for the update. I was unable to reproduce this yesterday, but that bit of info gives me a place to start. I'll update what I find.

**Comment by wrightp** [comment]
This is not a chef-ingredient issue. This is specific to chef server reconfigure and ipv6. Check that the chef server is configured for ipv6. Otherwise you can submit an issue to https://github.com/chef/chef-server

**Comment by gravesb** [comment]
I didn't realize you had to configure the server for ipv6, but now that you mention it I do see it in the docs here: https://docs.chef.io/config_rb_server.html. Thanks
