### ISSUE TITLE
chef-ingredient join-cluster setup

### ISSUE THREAD

**Issue by scopenco** [chef-cookbooks/chef-ingredient#142]
### Cookbook version
2.0.0

### Chef-client version
12.19.36

### Platform Details
CentOS 7.2

### Scenario:
I'm trying to configure chef server ha cluster based on last https://docs.chef.io/install_server_ha.html.  
The leader node I'm configuring with `chef_ingredient 'chef-backend'` and it starts as I need.    
The question is how can I join the second node to the leader? Of course, I can do it with `execute` like
```
execute 'chef-backend-ctl join-cluster IP --accept-license --yes --verbose'
```
but may exist some other more native way, based on chef-ingredient? Please advice.

**Comment by wrightp** [comment]
There is currently no native support for `chef-backend-ctl`. However, I like the idea. Perhaps we can add `chef-backend` support similar to the `omnibus_service` resource. For now, I suggest continuing with what you have.
