### ISSUE TITLE
Errors on converge on chef 12.5-12.6 with chef-ingredient 2.0.1

### ISSUE THREAD

**Issue by iennae** [chef-cookbooks/chef-ingredient#147]
Purely submitting this reported issue so that if anyone does a search they can find details about the fix.
### Cookbook version
Latest

### Chef-client version
12.5-12.6

### Platform Details
Any platform using chef 12.5 or 12.6

### Steps to Reproduce:
 Converge cookbook with Chef 12.5 or Chef 12.6 

### Expected Result:
Successful convergence.

### Actual Result:
         ================================================================================
           Error executing action `install` on resource 'chef_ingredient[chef-server]'
           ================================================================================
           NameError
           ---------
           No resource, method, or local variable named `check_deprecated_properties' for `LWRP resource chef_ingredient_chef_ingredient from cookbook chef-ingredient action provider "chef-server"'
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/chef-ingredient/resources/chef_ingredient.rb:68:in `block in class_from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/test/recipes/repo.rb
             2: chef_ingredient 'chef-server' do
             3:   config <<-EOS
             4: api_fqdn "#{node['fqdn']}"
             5: ip_version "ipv6"
             6: notification_email "#{node['chef_admin']}"
             7: nginx["ssl_protocols"] = "TLSv1 TLSv1.1 TLSv1.2"
             8: EOS
             9:   action :install
            10: end
            11:
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/test/recipes/repo.rb:2:in `from_file'
           chef_ingredient("chef-server") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :chef_ingredient
             cookbook_name "test"
             recipe_name "repo"
             config "api_fqdn \"default-ubuntu-1404.vagrantup.com\"\nip_version \"ipv6\"\nnotification_email \"\"\nnginx[\"ssl_protocols\"] = \"TLSv1 TLSv1.1 TLSv1.2\"\n"
           end
       Running handlers:
       [2017-04-11T20:18:56+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-04-11T20:18:56+00:00] ERROR: Exception handlers complete
       Chef Client failed. 3 resources updated in 21 seconds
       [2017-04-11T20:18:56+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-04-11T20:18:57+00:00] FATAL: NameError: chef_ingredient[chef-server] (test::repo line 2) had an error: NameError: No resource, method, or local variable named `check_deprecated_properties' for `LWRP resource chef_ingredient_chef_ingredient from cookbook chef-ingredient action provider "chef-server"'

**Comment by wrightp** [comment]
Thank you for reporting. This issue is confirmed. We encountered this last week. Fix is in progress.

**Comment by wrightp** [comment]
Fixed in 2.0.2
