### ISSUE TITLE
chef_client resource tries to load from chef_stack

### ISSUE THREAD

**Issue by palfrey** [chef-cookbooks/chef-ingredient#179]
### Cookbook version
2.1.2

### Chef-client version
12.12.15

### Platform Details
Ubuntu 14.04

### Scenario:
I want to install a chef client.

### Steps to Reproduce:
Use the chef_client resource

### Expected Result:
Chef client installs fine

### Actual Result:
"Cookbook chef_stack not found. If you're loading chef_stack from another cookbook, make sure you configure the dependency in your metadata"

Pretty sure this is because https://github.com/chef-cookbooks/chef-ingredient/blob/master/resources/client.rb#L86 which should be saying "chef-ingredient" not "chef_stack"

**Comment by tas50** [comment]
Fixed in https://github.com/chef-cookbooks/chef-ingredient/pull/186

**Comment by tas50** [comment]
Closing this out since it's been fixed and shipped
