### ISSUE TITLE
chef-ingredient 2.1.4 regression causes install failure on RHEL-5

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef-cookbooks/chef-ingredient#190]
### Cookbook version
2.1.5

### Chef-client version
13.2.20

### Platform Details
AWS RHEL-5

### Scenario:

chef-ingredient cookbook >= 2.1.4 now uses the yum provider instead of the rpm provider to install packages on RHEL platforms.

Reference:
[2.1.4 CHANGELOG](https://github.com/chef-cookbooks/chef-ingredient/blob/master/CHANGELOG.md#214-2017-07-27)
[Issue 181](https://github.com/chef-cookbooks/chef-ingredient/issues/181)
[PR 182](https://github.com/chef-cookbooks/chef-ingredient/pull/182)

RHEL-5's older version of yum has the gpgcheck option which is typically set to true in systems. When chef_ingredient uses yum to install a local package the gpg check is performed which fails because no key has been installed.

RHEL-6 and RHEL-7 have versions of yum that use a new localgpgcheck option. By default the localgpgcheck option won't check gpg signatures when installing local packages so chef_ingredient works fine for RHEL-6 and RHEL-7.

Here is a link to the change in yum which added the `localgpgcheck` option.

https://github.com/henrysher/yum/commit/290933489b1aaeb1017d10fb59ccf3231e309115

A workaround is to add the `options '--nogpgcheck'` property to the chef_ingredient resource when using chef-ingredient cookbook >= 2.1.4 on RHEL-5.

This seems like a regression though. Shouldn't the chef_ingredient resource be fixed so it automatically disables the gpgcheck when installing local packages on a RHEL-5 system?

### Steps to Reproduce:

```
chef_ingredient 'angry-omnibus-toolchain' do
  version '1.1.73'
  channel :stable
  architecture 'x86_64'
  platform_version_compatibility_mode true
  action :upgrade
end
```

### Expected Result:

I expect the angry-omnibus-toolchain package to be installed.

### Actual Result:

```
           * yum_package[angry-omnibus-toolchain] action upgrade

             ================================================================================
             Error executing action `upgrade` on resource 'yum_package[angry-omnibus-toolchain]'
             ================================================================================

             Chef::Exceptions::Exec
             ----------------------
             yum -d0 -e0 -y localinstall /tmp/kitchen/cache/angry-omnibus-toolchain-1.1.73-1.el5.x86_64.rpm returned 1:
             STDOUT:
             STDERR: warning: rpmts_HdrFromFdno: Header V3 DSA signature: NOKEY, key ID 83ef826a


             Public key for angry-omnibus-toolchain-1.1.73-1.el5.x86_64.rpm is not installed
```

**Comment by wrightp** [comment]
RHEL 5 is no longer supported
