### ISSUE TITLE
 /etc/chef/itu/chef-ingredient/libraries/omnibus_service_resource.rb:22: unknown type of %string

### ISSUE THREAD

**Issue by victoravr** [chef-cookbooks/chef-ingredient#22]
# knife cookbook upload chef-server --include-dependencies
Uploading chef-server    [4.0.0]
Uploading chef-ingredient [0.8.1]
FATAL: Cookbook file libraries/omnibus_service_resource.rb has a ruby syntax error:
FATAL: /etc/chef/itu/chef-ingredient/libraries/omnibus_service_resource.rb:22: unknown type of %string
FATAL:       actions %i(start stop restart hup int kill graceful_kill once)
FATAL:                  ^
FATAL: /etc/chef/itu/chef-ingredient/libraries/omnibus_service_resource.rb:22: syntax error, unexpected $end, expecting keyword_end
FATAL:       actions %i(start stop restart hup int kill graceful_kill once)
FATAL:                  ^

**Comment by victoravr** [comment]
Same for:
Tue Jul 21 16:46:43: (master) itu root# knife cookbook upload chef-server --include-dependencies
Uploading chef-server    [4.0.0]
Uploading chef-ingredient [0.8.1]
FATAL: Cookbook file libraries/omnibus_service_provider.rb has a ruby syntax error:
FATAL: /etc/chef/itu/chef-ingredient/libraries/omnibus_service_provider.rb:32: unknown type of %string
FATAL:       %i(start stop restart hup int ki...
FATAL:          ^
FATAL: /etc/chef/itu/chef-ingredient/libraries/omnibus_service_provider.rb:32: syntax error, unexpected $end, expecting keyword_end
FATAL:       %i(start stop restart hup int ki...
FATAL:

**Comment by ryancragun** [comment]
@victoravr the `%i` literal for an array of symbols was added in Ruby 2.0.0.  I suspect the version you're using is 1.9.3, thus you're seeing the syntax error.  The ChefDK comes bundled with a newer version so you shouldn't see this issue if you upgrade.

**Comment by jtimberman** [comment]
Chef 12.1 is required to use this cookbook (as now noted in the README.md on the master branch). We strongly recommend installing Chef using the omnibus installers - using the required version of Chef omnibus installer for 12.1.0+ will give you Ruby 2.1.4+.

https://github.com/chef/omnibus-chef/blob/chef-12.1.0/config/projects/chef.rb#L54
