### ISSUE TITLE
Supermarket does NOT use `supermarket.rb` as config file

### ISSUE THREAD

**Issue by afiune** [chef-cookbooks/chef-ingredient#30]
As a user I would like to use `chef_ingredient` and setup my supermarket server passing my configuration through the `config` attribute so I don't have to use other methods like a `template` or `file` resources to lay down my configuration.

**Proposal Solution**

Modify the `product_matrix` pointing to the right `config-file` that is `/etc/supermarket/supermarket.json`

**Comment by jtimberman** [comment]
Released in v0.10.1. Thanks!
