### ISSUE TITLE
Need to support better versioning than 'latest'

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/chef-ingredient#39]
For the client 'latest' doing major version upgrades is literally fucking awful.  People will see that and assume its a good idea and then will get hosed when Chef 13 comes out.

We need to steer people towards where 'latest' does only minor version upgrades and we have some kind of 'latest_with_major_upgrade' for times when you want to upgrade to the latest major version, or when you just really want to live yolo.

For upgrades of the client this should probably be done via just pulling the Chef::VERSION.to_i out of the running process, although I could see the case for having a different chef-solo/chef-zero that managed an omnibus chef-client install where you might want to poke `/opt/chef/embedded/bin/chef-client --version`.  For server and other packages, I guess you have to poke the ctl command or something?

Along with that omnitruck supports basically the '~>' operator via partial versions like "12" meaning "~> 12.0" and "12.4" meaning "~> 12.4.0".  We should figure out how to support that with the packages from packagecloud.  Its possible that the core chef package providers for yum and deb already do this (I seem to recall some issues about this but I wouldn't be too surprised if they were provider-specific and weren't remotely consistently implemented -- we should fix core chef if we have to in order to make this work right).

We should also make this work the same for both packagecloud and for mixlib-install.

**Comment by wrightp** [comment]
This is old, but we have added partial versioning support - 12, 12.1, etc
