### ISSUE TITLE
Need to optionally clean /opt/chef

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/chef-ingredient#47]
It causes issues when people upgrade and old gems are left in /opt/chef.

Doing this in the packaging violates the principle that the package should manage files outside of its packaged files.

So, the upgrade tool (chef_ingredient) must be responsible for this.

Because of the issues it can cause this should be enabled by default (but should be disable-able, in some cases its almost a feature since in most cases it makes upgrading faster since you don't have to reinstall all your chef_gems -- it just bites you on edge cases occasionally).

**Comment by lamont-granquist** [comment]
(and this is probably chef-client specific, i have no idea what the chef-server should do, but cleaning anything there outside of the package files seems like either a bad idea or something to be only done very carefully...)

**Comment by tas50** [comment]
Closing this out since we moved this cleanup into the omnibus configs.
