### ISSUE TITLE
chef-ingredient is currently broken

### ISSUE THREAD

**Issue by afiune** [chef-cookbooks/chef-ingredient#49]
There are some bugs on the actual code that I will try to debug and repair but one example is this line:

https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/chef_ingredient_provider.rb#L88

Where `package_name` does not even exist on the `resource` :sob: 

```
    ================================================================================
    Error executing action `reconfigure` on resource 'chef_ingredient[manage]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `package_name' for Chef::Resource::ChefIngredient

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:88:in `block in <class:ChefIngredient>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/chef-server-12/libraries/default.rb

     24:   chef_ingredient plugin
     25:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/chef-server-12/libraries/default.rb:24:in `install_plugin'

    chef_ingredient("manage") do
      action [:install]
      updated true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chef_ingredient
      cookbook_name "chef-server-12"
      recipe_name "default"
      product_name "manage"
      channel :stable
      version :latest
    end 
```

**Comment by xenolinguist** [comment]
Looks like `package_name` was renamed `product_name` in 1f6ab213f45903d7c22021ed02d43539434bc9f9 for #1. But it also looks like a lot of spots were left behind: https://github.com/chef-cookbooks/chef-ingredient/search?utf8=✓&q=package_name

**Comment by afiune** [comment]
Yup good catch @xenolinguist .. But I think some of them are correct. I think you are right but the only place missing is there one I mentioned. I am about to submit a PR but first I wanted to test it on a Delivery Cluster. :+1:

**Comment by afiune** [comment]
Fixed in favor of https://github.com/chef-cookbooks/chef-ingredient/pull/51
