### ISSUE TITLE
push-client package has been renamed

### ISSUE THREAD

**Issue by thenoid** [chef-cookbooks/chef-ingredient#61]
Starting with 1.3.3 the push jobs client package was renamed from:
opscode-push-jobs-client -> push-jobs-client

https://downloads.chef.io/push-jobs-client/redhat/

cookbook still calls it by it's original name.

https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/helpers.rb#L117

**Comment by thenoid** [comment]
Hmmm, looks like there is a PR for this open: https://github.com/chef-cookbooks/chef-ingredient/pull/60

**Comment by thenoid** [comment]
Though if v is set to '0.0.0' this #60 ends up setting it back to 'opscode-'....but seems like it should default to the new package name
```
      elsif (product == 'push-client') && (v < Mixlib::Versioning.parse('1.3.4') && (v > Mixlib::Versioning.parse('0.0.0')))
        data['package-name'] = 'opscode-push-jobs-client'
      elsif (product == 'push-client') && (v < Mixlib::Versioning.parse('2.0.0'))
        data['package-name'] = 'push-jobs-client'
```

**Comment by afiune** [comment]
I think this is fixed with https://github.com/chef-cookbooks/chef-ingredient/pull/66 

If not let me know and I will re open this issue ..
