### ISSUE TITLE
Policyfile run_list has non-existant recipe which prevents running kitchen suites

### ISSUE THREAD

**Issue by shanesveller** [chef-cookbooks/chef-ingredient#63]
I'm trying to take a stab at contributing a failing test case for `delivery-cli` on CentOS 6.6 due to an unsigned package, but I can't run any of the current or new kitchen suites to execute due to the following error:

```
Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error
       ================================================================================

       Chef::Exceptions::RecipeNotFound
       --------------------------------
       could not find recipe default for cookbook chef-ingredient
```

I noted that you cannot have an empty `run_list` in a Policyfile. What's the best approach to correct this and move forward?

**Comment by shanesveller** [comment]
For now I've adjusted the Policyfile to use `test::default` instead. I'm using ChefDK 0.10.0.

**Comment by shanesveller** [comment]
A few further experiments make it seem as though a `run_list` in the Policyfile overrides all run_list entries in the listed kitchen suites. I've tried adding a `named_run_list` in both the kitchen suite and Policyfile, but I'm either using incorrect syntax or that feature is not supported in `policyfile_zero` provisioner yet? The code looks as though this should be supported:
https://github.com/chef/chef-dk/blob/44b6ace69daf7b7f9e6a645d845b37d4e086ca0f/lib/kitchen/provisioner/policyfile_zero.rb#L115

**Comment by schisamo** [comment]
@danielsdeleo what's the deal here? Policyfile won't let you leave the `run_list` out:

```
2.1.6p336 in ~/d/c/e/r/c/chef-ingredient on schisamo/fix-push-jobs-client ✗
➜  cat Policyfile.rb
name 'chef-ingredient'
# run_list 'test::default'
default_source :community

cookbook 'chef-ingredient', path: '.'

cookbook 'test', path: './test/fixtures/cookbooks/test'
2.1.6p336 in ~/d/c/e/r/c/chef-ingredient on schisamo/fix-push-jobs-client ✗
➜  chef install
Error: Failed to generate Policyfile.lock
Reason: (ChefDK::PolicyfileError) Invalid run_list. run_list cannot be empty
```

Yet the run lists you set in your `.kitchen.yml` suites are not respected.

**Comment by danielsdeleo** [comment]
You're supposed to use `named_run_lists` for suites, but this feature is only implemented in master right now. You can't use arbitrary run lists with policyfiles because they might refer to cookbooks outside of the locked set. This is built-in to the behavior of chef-client when running under policyfile mode--it ignores run lists from other sources. Note that you will have to put `named_run_list` under the `provisioner:` scope in the kitchen yaml for reasons I described here (also shows a valid example): https://github.com/chef/chef-dk/pull/607

**Comment by shanesveller** [comment]
@danielsdeleo @schisamo Thank you both for the responses!

**Comment by shanesveller** [comment]
I'm not able to try running against `master` right now, but if that's already fixed and will end up in the release pipeline, we can close this out.
