### ISSUE TITLE
GPG error

### ISSUE THREAD

**Issue by stephenlauck** [chef-cookbooks/chef-ingredient#76]
Consistently getting this error:

`W: GPG error: https://packagecloud.io trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 37BBEE3F7AD95B3F`

When trying to install chef-server using chef-ingredient.

**Comment by vinyar** [comment]
I get the same error sporadically.

**Comment by thommay** [comment]
I think we can close this now that PackageCloud is no more.
