### ISSUE TITLE
Installing chef-server using ChefDK 0.10.0 failed

### ISSUE THREAD

**Issue by DeWaRs1206** [chef-cookbooks/chef-ingredient#83]
Hi,

When I try to install chef-server using chefdk 0.10.0, the execution failed with the following log : 

================================================================================
Error executing action `install` on resource 'chef_gem[mixlib-install]'
================================================================================

Errno::EPIPE
------------
Broken pipe @ io_write - <STDERR>

Cookbook Trace:
---------------
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:120:in `install_gem_from_rubygems'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:104:in `ensure_mixlib_install_gem_installed!'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:40:in `ingredient_package_name'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:67:in `block in configure_package'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:65:in `configure_package'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:21:in `handle_install'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:54:in `block in <class:ChefIngredient>'

Compiled Resource:
------------------
# Declared in

chef_gem("mixlib-install") do
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  package_name "mixlib-install"
  version "0.8.0.alpha.2"
  gem_binary "/opt/chefdk/embedded/bin/gem"
end

================================================================================
Error executing action `install` on resource 'chef_ingredient[chef-server]'
================================================================================

Errno::EPIPE
------------
chef_gem[mixlib-install] (dynamically defined) had an error: Errno::EPIPE: Broken pipe @ io_write - <STDERR>

Cookbook Trace:
---------------
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:120:in `install_gem_from_rubygems'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:104:in `ensure_mixlib_install_gem_installed!'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:40:in `ingredient_package_name'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:67:in `block in configure_package'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:65:in `configure_package'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:21:in `handle_install'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:54:in `block in <class:ChefIngredient>'

Resource Declaration:
---------------------
# In /var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-server/recipes/default.rb

 26: chef_ingredient 'chef-server' do
 27:   extend ChefServerCookbook::Helpers
 28:   version node['chef-server']['version']
 29:   package_source node['chef-server']['package_source']
 30:   config <<-EOS
 31: topology "#{node['chef-server']['topology']}"
 32: #{"api_fqdn \"#{node['chef-server']['api_fqdn']}\"" if api_fqdn_available?}
 33: #{node['chef-server']['configuration']}
 34: EOS
 35:   action :install
 36: end
 37:

Compiled Resource:
------------------
# Declared in /var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-server/recipes/default.rb:26:in `from_file'

chef_ingredient("chef-server") do
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :chef_ingredient
  cookbook_name :"chef-server"
  recipe_name "default"
  config "topology \"standalone\"\napi_fqdn \"mo-78d3593f9.mo.sap.corp\"\n\n"
  product_name "chef-server"
end

[2016-02-19T13:48:58+00:00] INFO: Running queued delayed notifications before re-raising exception
[2016-02-19T13:48:58+00:00] DEBUG: Re-raising exception: Errno::EPIPE - chef_ingredient[chef-server] (chef-server::default line 26) had an error: Errno::EPIPE: chef_gem[mixlib-install] (dynamically defined) had an error: Errno::EPIPE: Broken pipe @ io_write - <STDERR>
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1168:in `write'
  /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1168:in `warn'
  /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1168:in `reset'
  /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:882:in `dirs='
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:297:in `gem_specification'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:90:in `installed_versions'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:454:in `matching_installed_versions'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:437:in `current_version'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:470:in `load_current_resource'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:127:in `run_action'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:588:in `run_action'
  /var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:120:in `install_gem_from_rubygems'
  /var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:104:in `ensure_mixlib_install_gem_installed!'
  /var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:40:in `ingredient_package_name'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:1577:in `method_missing'
  /var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:67:in `block in configure_package'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_builder.rb:77:in `instance_eval'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_builder.rb:77:in `build'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/dsl/recipe.rb:108:in `build_resource'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/dsl/recipe.rb:69:in `declare_resource'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/dsl/resources.rb:15:in `package'
  /var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:65:in `configure_package'
  /var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:21:in `handle_install'
  /var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:54:in `block in <class:ChefIngredient>'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:362:in `action_install'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:588:in `run_action'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:53:in `run_action'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:85:in `block (2 levels) in converge'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:85:in `each'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:85:in `block in converge'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:84:in `converge'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `block in converge'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `catch'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `converge'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:687:in `converge_and_save'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:269:in `run'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:269:in `loop'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:247:in `run_application'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-solo:25:in `<top (required)>'
  /opt/chefdk/bin/chef-solo:54:in `load'
  /opt/chefdk/bin/chef-solo:54:in `<main>'
[2016-02-19T13:48:58+00:00] ERROR: Running exception handlers
[2016-02-19T13:48:58+00:00] ERROR: Exception handlers complete
[2016-02-19T13:48:58+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-02-19T13:48:58+00:00] DEBUG: Errno::EPIPE: chef_ingredient[chef-server] (chef-server::default line 26) had an error: Errno::EPIPE: chef_gem[mixlib-install] (dynamically defined) had an error: Errno::EPIPE: Broken pipe @ io_write - <STDERR>
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1168:in `write'
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1168:in `warn'
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1168:in `reset'
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:882:in `dirs='
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:297:in `gem_specification'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:90:in `installed_versions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:454:in `matching_installed_versions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:437:in `current_version'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/rubygems.rb:470:in `load_current_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:127:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:588:in `run_action'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:120:in `install_gem_from_rubygems'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:104:in `ensure_mixlib_install_gem_installed!'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/helpers.rb:40:in `ingredient_package_name'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:1577:in `method_missing'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:67:in `block in configure_package'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_builder.rb:77:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_builder.rb:77:in `build'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/dsl/recipe.rb:108:in `build_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/dsl/recipe.rb:69:in `declare_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/dsl/resources.rb:15:in `package'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:65:in `configure_package'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/rhel_handler.rb:21:in `handle_install'
/var/lib/monsoon/repos/devops_automation/manu_chef_server/chef/site-cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb:54:in `block in <class:ChefIngredient>'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:362:in `action_install'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:588:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:53:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:85:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:85:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:85:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:84:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `catch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:687:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:269:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:269:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/solo.rb:247:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-solo:25:in `<top (required)>'
/opt/chefdk/bin/chef-solo:54:in `load'
/opt/chefdk/bin/chef-solo:54:in `<main>'
[2016-02-19T13:48:58+00:00] ERROR: chef_ingredient[chef-server] (chef-server::default line 26) had an error: Errno::EPIPE: chef_gem[mixlib-install] (dynamically defined) had an error: Errno::EPIPE: Broken pipe @ io_write - <STDERR>

When I try using chef-client 12.5.1 from the official package, it works correctly. 

Any idea anyone ?

**Comment by DeWaRs1206** [comment]
I notice something, on a instance with chefDK installed : 
[root@DEWDFLMLCHEFDK bin]# ./gem install mixlib-install -v 0.8.0.alpha.2
WARNING:  You don't have /root/.chefdk/gem/ruby/2.1.0/bin in your PATH,
	  gem executables will not run.
Successfully installed mixlib-install-0.8.0.alpha.2
1 gem installed
[root@DEWDFLMLCHEFDK bin]#

On an instance with chef-client : 

[root@DEWDFLMLCHEFCL bin]# ./gem install mixlib-install -v 0.8.0.alpha.2
Successfully installed mixlib-install-0.8.0.alpha.2
Parsing documentation for mixlib-install-0.8.0.alpha.2
Installing ri documentation for mixlib-install-0.8.0.alpha.2
Done installing documentation for mixlib-install after 0 seconds
1 gem installed

The warning break the automation with chefDK

**Comment by wrightp** [comment]
no longer specifying alpha versions. Closing.
